export const data =[
    { "search_value": "Antibiotics" },
    { "search_value": "Albuterol" },
    { "search_value": "Antihistamines" },
    { "search_value": "Bandy-Plus" },
    { "search_value": "Benadryl Syrup" },
    { "search_value": "Broclear Tablet" },
    { "search_value": "Bilazest 20mg" },
    { "search_value": "Crocin Advance" },
    { "search_value": "Candiforce 200 Capsule" },
    { "search_value": "Dolo 650" },
    { "search_value": "Derobin Ointment" },
    { "search_value": "Enzoflam" },
    { "search_value": "Emeset" },
    { "search_value": "Hydrocodone" },
    { "search_value": "Eliwel 10mg" },
    { "search_value": "Flexon" },
    { "search_value": "Folitrax" },
    { "search_value": "Fludac Capsule" },
    { "search_value": "Glyciphage SR 500mg " },
    { "search_value": "Gemer 2 Tablet PR" },
    { "search_value": "Grisovin-FP " },
    { "search_value": "Gudlax-Plus Laxative Peppermint Sugar Free" },
    { "search_value": "Human Actrapid 40IU/ml Solution" },
    { "search_value": "Hylosoft Eye Drop" },
    { "search_value": "Hyperneb 3% Respules (4ml Each)" },
    { "search_value": "Indocap SR Capsule" },
    { "search_value": "Isotroin 20 Capsule" },
    { "search_value": "Influvac Tetra 2022 Vaccine" },
    { "search_value": "Jupiros 10 " },
    { "search_value": "Ketorol-DT" },
    { "search_value": "Kutub 30 X " },
    { "search_value": "Keralin Ointment" },
    { "search_value": "Librax 5 mg/2.5 mg Tablet" },
    { "search_value": "Levocet" }
  ];
  